// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Program struct {
	ID                string             `json:"id"`
	MerchantID        string             `json:"merchant_id"`
	MerchantName      string             `json:"merchant_name"`
	Lat               float64            `json:"lat"`
	Lng               float64            `json:"lng"`
	StampGoal         int32              `json:"stamp_goal"`
	RewardName        string             `json:"reward_name"`
	RewardImageUrl    pgtype.Text        `json:"reward_image_url"`
	RewardDescription string             `json:"reward_description"`
	Description       string             `json:"description"`
	Rules             string             `json:"rules"`
	Active            bool               `json:"active"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	EndsAt            pgtype.Timestamptz `json:"ends_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type QrCode struct {
	ID           string             `json:"id"`
	ProgramID    string             `json:"program_id"`
	MerchantID   string             `json:"merchant_id"`
	CodeHash     string             `json:"code_hash"`
	RawPayload   string             `json:"raw_payload"`
	GeneratedAt  pgtype.Timestamptz `json:"generated_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	Used         bool               `json:"used"`
	UsedByUserID pgtype.Text        `json:"used_by_user_id"`
	UsedAt       pgtype.Timestamptz `json:"used_at"`
}

type RewardRedemption struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	ProgramID   string             `json:"program_id"`
	RewardCode  string             `json:"reward_code"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Redeemed    bool               `json:"redeemed"`
	RedeemedAt  pgtype.Timestamptz `json:"redeemed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Stamp struct {
	ID            string             `json:"id"`
	UserID        string             `json:"user_id"`
	ProgramID     string             `json:"program_id"`
	QrCodeID      string             `json:"qr_code_id"`
	QrCodeHash    string             `json:"qr_code_hash"`
	AcquiredAt    pgtype.Timestamptz `json:"acquired_at"`
	ValidationKey string             `json:"validation_key"`
	Sequence      int32              `json:"sequence"`
	Validated     bool               `json:"validated"`
}

type User struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	ProfileImageUrl pgtype.Text        `json:"profile_image_url"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
