// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: programs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNearbyPrograms = `-- name: CountNearbyPrograms :one
SELECT COUNT(*)::bigint
FROM programs p
WHERE p.active = TRUE
  AND p.starts_at <= now()
  AND (p.ends_at IS NULL OR p.ends_at >= now())
  AND ST_DWithin(
    ST_SetSRID(ST_MakePoint(p.lng, p.lat), 4326)::geography,
    ST_SetSRID(ST_MakePoint($1, $2), 4326)::geography,
    $3
    )
`

type CountNearbyProgramsParams struct {
	Lng          interface{} `json:"lng"`
	Lat          interface{} `json:"lat"`
	RadiusMeters interface{} `json:"radius_meters"`
}

func (q *Queries) CountNearbyPrograms(ctx context.Context, arg CountNearbyProgramsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNearbyPrograms, arg.Lng, arg.Lat, arg.RadiusMeters)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getLastProgramStamp = `-- name: GetLastProgramStamp :one
SELECT
    p.id AS program_id,
    p.merchant_name,
    p.stamp_goal,
    totals.obtained_stamps,
    st.id AS stamp_id,
    st.user_id,
    st.program_id AS stamp_program_id,
    st.acquired_at,
    st.validation_key,
    st.sequence,
    st.validated
FROM stamps st
JOIN programs p ON p.id = st.program_id
JOIN LATERAL (
    SELECT COUNT(*)::int AS obtained_stamps
    FROM stamps sx
    WHERE sx.user_id = st.user_id
      AND sx.program_id = st.program_id
) totals ON TRUE
WHERE st.user_id = $1
ORDER BY st.acquired_at DESC
LIMIT 1
`

type GetLastProgramStampRow struct {
	ProgramID      string             `json:"program_id"`
	MerchantName   string             `json:"merchant_name"`
	StampGoal      int32              `json:"stamp_goal"`
	ObtainedStamps int32              `json:"obtained_stamps"`
	StampID        string             `json:"stamp_id"`
	UserID         string             `json:"user_id"`
	StampProgramID string             `json:"stamp_program_id"`
	AcquiredAt     pgtype.Timestamptz `json:"acquired_at"`
	ValidationKey  string             `json:"validation_key"`
	Sequence       int32              `json:"sequence"`
	Validated      bool               `json:"validated"`
}

func (q *Queries) GetLastProgramStamp(ctx context.Context, userID string) (GetLastProgramStampRow, error) {
	row := q.db.QueryRow(ctx, getLastProgramStamp, userID)
	var i GetLastProgramStampRow
	err := row.Scan(
		&i.ProgramID,
		&i.MerchantName,
		&i.StampGoal,
		&i.ObtainedStamps,
		&i.StampID,
		&i.UserID,
		&i.StampProgramID,
		&i.AcquiredAt,
		&i.ValidationKey,
		&i.Sequence,
		&i.Validated,
	)
	return i, err
}

const getProgramDetail = `-- name: GetProgramDetail :one
SELECT
    p.id,
    p.merchant_name,
    p.lat,
    p.lng,
    p.stamp_goal,
    COALESCE((
        SELECT COUNT(*)::int
        FROM stamps st
        WHERE st.program_id = p.id
          AND st.user_id = $2
    ), 0)::int AS current_stamps,
    p.reward_name,
    p.reward_image_url,
    p.reward_description,
    p.description,
    p.rules,
    p.active,
    p.starts_at,
    p.ends_at
FROM programs p
WHERE p.id = $1
`

type GetProgramDetailParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type GetProgramDetailRow struct {
	ID                string             `json:"id"`
	MerchantName      string             `json:"merchant_name"`
	Lat               float64            `json:"lat"`
	Lng               float64            `json:"lng"`
	StampGoal         int32              `json:"stamp_goal"`
	CurrentStamps     int32              `json:"current_stamps"`
	RewardName        string             `json:"reward_name"`
	RewardImageUrl    pgtype.Text        `json:"reward_image_url"`
	RewardDescription string             `json:"reward_description"`
	Description       string             `json:"description"`
	Rules             string             `json:"rules"`
	Active            bool               `json:"active"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	EndsAt            pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) GetProgramDetail(ctx context.Context, arg GetProgramDetailParams) (GetProgramDetailRow, error) {
	row := q.db.QueryRow(ctx, getProgramDetail, arg.ID, arg.UserID)
	var i GetProgramDetailRow
	err := row.Scan(
		&i.ID,
		&i.MerchantName,
		&i.Lat,
		&i.Lng,
		&i.StampGoal,
		&i.CurrentStamps,
		&i.RewardName,
		&i.RewardImageUrl,
		&i.RewardDescription,
		&i.Description,
		&i.Rules,
		&i.Active,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const getRewardRedemptionByProgram = `-- name: GetRewardRedemptionByProgram :one
SELECT id, user_id, program_id, reward_code, completed_at, expires_at, redeemed, redeemed_at, created_at
FROM reward_redemptions
WHERE user_id = $1
  AND program_id = $2
`

type GetRewardRedemptionByProgramParams struct {
	UserID    string `json:"user_id"`
	ProgramID string `json:"program_id"`
}

func (q *Queries) GetRewardRedemptionByProgram(ctx context.Context, arg GetRewardRedemptionByProgramParams) (RewardRedemption, error) {
	row := q.db.QueryRow(ctx, getRewardRedemptionByProgram, arg.UserID, arg.ProgramID)
	var i RewardRedemption
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProgramID,
		&i.RewardCode,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.Redeemed,
		&i.RedeemedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveUserPrograms = `-- name: ListActiveUserPrograms :many
SELECT
    p.id AS program_id,
    p.merchant_name,
    p.stamp_goal,
    COUNT(st.id)::int AS obtained_stamps,
    GREATEST(p.stamp_goal - COUNT(st.id), 0)::int AS remaining_stamps,
    LEAST(100, FLOOR((COUNT(st.id)::numeric / p.stamp_goal) * 100))::int AS progress,
    MAX(st.acquired_at)::timestamptz AS last_stamp_at,
    (COUNT(st.id) = p.stamp_goal - 1) AS almost_complete,
    p.reward_name,
    p.reward_image_url,
    p.reward_description
FROM programs p
JOIN stamps st ON st.program_id = p.id
WHERE st.user_id = $1
  AND p.active = TRUE
  AND (p.ends_at IS NULL OR p.ends_at >= now())
GROUP BY p.id
HAVING COUNT(st.id) > 0 AND COUNT(st.id) < p.stamp_goal
ORDER BY MAX(st.acquired_at) DESC
`

type ListActiveUserProgramsRow struct {
	ProgramID         string             `json:"program_id"`
	MerchantName      string             `json:"merchant_name"`
	StampGoal         int32              `json:"stamp_goal"`
	ObtainedStamps    int32              `json:"obtained_stamps"`
	RemainingStamps   int32              `json:"remaining_stamps"`
	Progress          int32              `json:"progress"`
	LastStampAt       pgtype.Timestamptz `json:"last_stamp_at"`
	AlmostComplete    bool               `json:"almost_complete"`
	RewardName        string             `json:"reward_name"`
	RewardImageUrl    pgtype.Text        `json:"reward_image_url"`
	RewardDescription string             `json:"reward_description"`
}

func (q *Queries) ListActiveUserPrograms(ctx context.Context, userID string) ([]ListActiveUserProgramsRow, error) {
	rows, err := q.db.Query(ctx, listActiveUserPrograms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveUserProgramsRow{}
	for rows.Next() {
		var i ListActiveUserProgramsRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.MerchantName,
			&i.StampGoal,
			&i.ObtainedStamps,
			&i.RemainingStamps,
			&i.Progress,
			&i.LastStampAt,
			&i.AlmostComplete,
			&i.RewardName,
			&i.RewardImageUrl,
			&i.RewardDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableRewards = `-- name: ListAvailableRewards :many
SELECT
    rr.program_id,
    p.merchant_name,
    p.reward_name,
    p.reward_image_url,
    p.reward_description,
    rr.completed_at,
    rr.expires_at
FROM reward_redemptions rr
JOIN programs p ON p.id = rr.program_id
WHERE rr.user_id = $1
  AND rr.redeemed = FALSE
  AND (rr.expires_at IS NULL OR rr.expires_at > now())
ORDER BY rr.completed_at DESC
`

type ListAvailableRewardsRow struct {
	ProgramID         string             `json:"program_id"`
	MerchantName      string             `json:"merchant_name"`
	RewardName        string             `json:"reward_name"`
	RewardImageUrl    pgtype.Text        `json:"reward_image_url"`
	RewardDescription string             `json:"reward_description"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListAvailableRewards(ctx context.Context, userID string) ([]ListAvailableRewardsRow, error) {
	rows, err := q.db.Query(ctx, listAvailableRewards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableRewardsRow{}
	for rows.Next() {
		var i ListAvailableRewardsRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.MerchantName,
			&i.RewardName,
			&i.RewardImageUrl,
			&i.RewardDescription,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinishedUserPrograms = `-- name: ListFinishedUserPrograms :many
WITH progress AS (
    SELECT
        p.id AS program_id,
        p.merchant_name,
        p.stamp_goal,
        COUNT(st.id)::int AS obtained_stamps,
        MAX(st.acquired_at) AS last_stamp_at,
        p.ends_at,
        p.reward_name,
        p.reward_image_url,
        p.reward_description,
        rr.redeemed,
        rr.redeemed_at,
        rr.completed_at
    FROM programs p
    JOIN stamps st ON st.program_id = p.id
    LEFT JOIN reward_redemptions rr ON rr.program_id = p.id AND rr.user_id = $1
    WHERE st.user_id = $1
    GROUP BY p.id, rr.redeemed, rr.redeemed_at, rr.completed_at
), classified AS (
    SELECT
        program_id,
        merchant_name,
        reward_name,
        reward_image_url,
        reward_description,
        CASE
            WHEN redeemed THEN 'resgatado'
            WHEN obtained_stamps >= stamp_goal THEN 'completo'
            WHEN ends_at IS NOT NULL AND ends_at < now() THEN 'expirado'
            ELSE NULL
        END::text AS status,
        COALESCE(completed_at, ends_at, last_stamp_at) AS finished_at,
        redeemed,
        redeemed_at
    FROM progress
    WHERE obtained_stamps >= stamp_goal
       OR (ends_at IS NOT NULL AND ends_at < now())
)
SELECT
    program_id,
    merchant_name,
    reward_name,
    reward_image_url,
    reward_description,
    status,
    finished_at,
    redeemed,
    redeemed_at
FROM classified
WHERE status IS NOT NULL
  AND ($2::text = '' OR status = $2::text)
ORDER BY finished_at DESC
`

type ListFinishedUserProgramsParams struct {
	UserID       string `json:"user_id"`
	FilterStatus string `json:"filter_status"`
}

type ListFinishedUserProgramsRow struct {
	ProgramID         string             `json:"program_id"`
	MerchantName      string             `json:"merchant_name"`
	RewardName        string             `json:"reward_name"`
	RewardImageUrl    pgtype.Text        `json:"reward_image_url"`
	RewardDescription string             `json:"reward_description"`
	Status            string             `json:"status"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	Redeemed          pgtype.Bool        `json:"redeemed"`
	RedeemedAt        pgtype.Timestamptz `json:"redeemed_at"`
}

func (q *Queries) ListFinishedUserPrograms(ctx context.Context, arg ListFinishedUserProgramsParams) ([]ListFinishedUserProgramsRow, error) {
	rows, err := q.db.Query(ctx, listFinishedUserPrograms, arg.UserID, arg.FilterStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFinishedUserProgramsRow{}
	for rows.Next() {
		var i ListFinishedUserProgramsRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.MerchantName,
			&i.RewardName,
			&i.RewardImageUrl,
			&i.RewardDescription,
			&i.Status,
			&i.FinishedAt,
			&i.Redeemed,
			&i.RedeemedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNearbyPrograms = `-- name: ListNearbyPrograms :many
SELECT
    p.id,
    p.merchant_name,
    p.lat,
    p.lng,
    ST_Distance(
        ST_SetSRID(ST_MakePoint(p.lng, p.lat), 4326)::geography,
        ST_SetSRID(ST_MakePoint($1, $2), 4326)::geography
    )::double precision AS distance,
    p.stamp_goal,
    COALESCE((
        SELECT COUNT(*)::int
        FROM stamps st
        WHERE st.program_id = p.id
                    AND st.user_id = $3
    ), 0)::int AS current_stamps,
    p.reward_name,
    p.reward_image_url,
    p.reward_description,
    p.description,
    p.rules,
    p.active,
    p.starts_at,
    p.ends_at
FROM programs p
WHERE p.active = TRUE
  AND p.starts_at <= now()
  AND (p.ends_at IS NULL OR p.ends_at >= now())
  AND ST_DWithin(
        ST_SetSRID(ST_MakePoint(p.lng, p.lat), 4326)::geography,
                ST_SetSRID(ST_MakePoint($1, $2), 4326)::geography,
                $4
    )
ORDER BY distance ASC, p.created_at DESC
LIMIT $6 OFFSET $5
`

type ListNearbyProgramsParams struct {
	Lng          interface{} `json:"lng"`
	Lat          interface{} `json:"lat"`
	UserID       string      `json:"user_id"`
	RadiusMeters interface{} `json:"radius_meters"`
	OffsetRows   int32       `json:"offset_rows"`
	LimitRows    int32       `json:"limit_rows"`
}

type ListNearbyProgramsRow struct {
	ID                string             `json:"id"`
	MerchantName      string             `json:"merchant_name"`
	Lat               float64            `json:"lat"`
	Lng               float64            `json:"lng"`
	Distance          float64            `json:"distance"`
	StampGoal         int32              `json:"stamp_goal"`
	CurrentStamps     int32              `json:"current_stamps"`
	RewardName        string             `json:"reward_name"`
	RewardImageUrl    pgtype.Text        `json:"reward_image_url"`
	RewardDescription string             `json:"reward_description"`
	Description       string             `json:"description"`
	Rules             string             `json:"rules"`
	Active            bool               `json:"active"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	EndsAt            pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) ListNearbyPrograms(ctx context.Context, arg ListNearbyProgramsParams) ([]ListNearbyProgramsRow, error) {
	rows, err := q.db.Query(ctx, listNearbyPrograms,
		arg.Lng,
		arg.Lat,
		arg.UserID,
		arg.RadiusMeters,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNearbyProgramsRow{}
	for rows.Next() {
		var i ListNearbyProgramsRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantName,
			&i.Lat,
			&i.Lng,
			&i.Distance,
			&i.StampGoal,
			&i.CurrentStamps,
			&i.RewardName,
			&i.RewardImageUrl,
			&i.RewardDescription,
			&i.Description,
			&i.Rules,
			&i.Active,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemReward = `-- name: RedeemReward :one
UPDATE reward_redemptions
SET redeemed = TRUE,
    redeemed_at = now()
WHERE user_id = $1
  AND program_id = $2
  AND reward_code = $3
  AND redeemed = FALSE
RETURNING redeemed_at
`

type RedeemRewardParams struct {
	UserID     string `json:"user_id"`
	ProgramID  string `json:"program_id"`
	RewardCode string `json:"reward_code"`
}

func (q *Queries) RedeemReward(ctx context.Context, arg RedeemRewardParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, redeemReward, arg.UserID, arg.ProgramID, arg.RewardCode)
	var redeemed_at pgtype.Timestamptz
	err := row.Scan(&redeemed_at)
	return redeemed_at, err
}

const upsertRewardRedemption = `-- name: UpsertRewardRedemption :one
INSERT INTO reward_redemptions (
    id,
    user_id,
    program_id,
    reward_code,
    completed_at,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (user_id, program_id) DO UPDATE
SET user_id = EXCLUDED.user_id
RETURNING id, user_id, program_id, reward_code, completed_at, expires_at, redeemed, redeemed_at, created_at
`

type UpsertRewardRedemptionParams struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	ProgramID   string             `json:"program_id"`
	RewardCode  string             `json:"reward_code"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertRewardRedemption(ctx context.Context, arg UpsertRewardRedemptionParams) (RewardRedemption, error) {
	row := q.db.QueryRow(ctx, upsertRewardRedemption,
		arg.ID,
		arg.UserID,
		arg.ProgramID,
		arg.RewardCode,
		arg.CompletedAt,
		arg.ExpiresAt,
	)
	var i RewardRedemption
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProgramID,
		&i.RewardCode,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.Redeemed,
		&i.RedeemedAt,
		&i.CreatedAt,
	)
	return i, err
}
