// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stamps.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStampsByProgram = `-- name: CountStampsByProgram :one
SELECT COUNT(*)::int
FROM stamps
WHERE user_id = $1
  AND program_id = $2
`

type CountStampsByProgramParams struct {
	UserID    string `json:"user_id"`
	ProgramID string `json:"program_id"`
}

func (q *Queries) CountStampsByProgram(ctx context.Context, arg CountStampsByProgramParams) (int32, error) {
	row := q.db.QueryRow(ctx, countStampsByProgram, arg.UserID, arg.ProgramID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createStamp = `-- name: CreateStamp :one
INSERT INTO stamps (
    id,
    user_id,
    program_id,
    qr_code_id,
    qr_code_hash,
    validation_key,
    sequence
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, user_id, program_id, acquired_at, validation_key, sequence, validated
`

type CreateStampParams struct {
	ID            string `json:"id"`
	UserID        string `json:"user_id"`
	ProgramID     string `json:"program_id"`
	QrCodeID      string `json:"qr_code_id"`
	QrCodeHash    string `json:"qr_code_hash"`
	ValidationKey string `json:"validation_key"`
	Sequence      int32  `json:"sequence"`
}

type CreateStampRow struct {
	ID            string             `json:"id"`
	UserID        string             `json:"user_id"`
	ProgramID     string             `json:"program_id"`
	AcquiredAt    pgtype.Timestamptz `json:"acquired_at"`
	ValidationKey string             `json:"validation_key"`
	Sequence      int32              `json:"sequence"`
	Validated     bool               `json:"validated"`
}

func (q *Queries) CreateStamp(ctx context.Context, arg CreateStampParams) (CreateStampRow, error) {
	row := q.db.QueryRow(ctx, createStamp,
		arg.ID,
		arg.UserID,
		arg.ProgramID,
		arg.QrCodeID,
		arg.QrCodeHash,
		arg.ValidationKey,
		arg.Sequence,
	)
	var i CreateStampRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProgramID,
		&i.AcquiredAt,
		&i.ValidationKey,
		&i.Sequence,
		&i.Validated,
	)
	return i, err
}

const findStampByQRCodeHash = `-- name: FindStampByQRCodeHash :one
SELECT id
FROM stamps
WHERE qr_code_hash = $1
`

func (q *Queries) FindStampByQRCodeHash(ctx context.Context, qrCodeHash string) (string, error) {
	row := q.db.QueryRow(ctx, findStampByQRCodeHash, qrCodeHash)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getMaxStampSequence = `-- name: GetMaxStampSequence :one
SELECT COALESCE(MAX(sequence), 0)::int
FROM stamps
WHERE user_id = $1
  AND program_id = $2
`

type GetMaxStampSequenceParams struct {
	UserID    string `json:"user_id"`
	ProgramID string `json:"program_id"`
}

func (q *Queries) GetMaxStampSequence(ctx context.Context, arg GetMaxStampSequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxStampSequence, arg.UserID, arg.ProgramID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getQRCodeValidation = `-- name: GetQRCodeValidation :one
SELECT
    q.id,
    q.program_id,
    q.merchant_id,
    q.code_hash,
    q.raw_payload,
    q.generated_at,
    q.expires_at,
    q.used,
    q.used_by_user_id,
    q.used_at,
    p.merchant_name,
    p.stamp_goal,
    p.reward_name,
    p.reward_image_url,
    p.reward_description
FROM qr_codes q
JOIN programs p ON p.id = q.program_id
WHERE q.code_hash = $1
`

type GetQRCodeValidationRow struct {
	ID                string             `json:"id"`
	ProgramID         string             `json:"program_id"`
	MerchantID        string             `json:"merchant_id"`
	CodeHash          string             `json:"code_hash"`
	RawPayload        string             `json:"raw_payload"`
	GeneratedAt       pgtype.Timestamptz `json:"generated_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Used              bool               `json:"used"`
	UsedByUserID      pgtype.Text        `json:"used_by_user_id"`
	UsedAt            pgtype.Timestamptz `json:"used_at"`
	MerchantName      string             `json:"merchant_name"`
	StampGoal         int32              `json:"stamp_goal"`
	RewardName        string             `json:"reward_name"`
	RewardImageUrl    pgtype.Text        `json:"reward_image_url"`
	RewardDescription string             `json:"reward_description"`
}

func (q *Queries) GetQRCodeValidation(ctx context.Context, codeHash string) (GetQRCodeValidationRow, error) {
	row := q.db.QueryRow(ctx, getQRCodeValidation, codeHash)
	var i GetQRCodeValidationRow
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.MerchantID,
		&i.CodeHash,
		&i.RawPayload,
		&i.GeneratedAt,
		&i.ExpiresAt,
		&i.Used,
		&i.UsedByUserID,
		&i.UsedAt,
		&i.MerchantName,
		&i.StampGoal,
		&i.RewardName,
		&i.RewardImageUrl,
		&i.RewardDescription,
	)
	return i, err
}

const listStampsByProgram = `-- name: ListStampsByProgram :many
SELECT
    st.id,
    st.user_id,
    st.program_id,
    st.acquired_at,
    st.validation_key,
    st.sequence,
    st.validated,
    p.merchant_name
FROM stamps st
JOIN programs p ON p.id = st.program_id
WHERE st.user_id = $1
  AND st.program_id = $2
ORDER BY st.sequence ASC
`

type ListStampsByProgramParams struct {
	UserID    string `json:"user_id"`
	ProgramID string `json:"program_id"`
}

type ListStampsByProgramRow struct {
	ID            string             `json:"id"`
	UserID        string             `json:"user_id"`
	ProgramID     string             `json:"program_id"`
	AcquiredAt    pgtype.Timestamptz `json:"acquired_at"`
	ValidationKey string             `json:"validation_key"`
	Sequence      int32              `json:"sequence"`
	Validated     bool               `json:"validated"`
	MerchantName  string             `json:"merchant_name"`
}

func (q *Queries) ListStampsByProgram(ctx context.Context, arg ListStampsByProgramParams) ([]ListStampsByProgramRow, error) {
	rows, err := q.db.Query(ctx, listStampsByProgram, arg.UserID, arg.ProgramID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStampsByProgramRow{}
	for rows.Next() {
		var i ListStampsByProgramRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProgramID,
			&i.AcquiredAt,
			&i.ValidationKey,
			&i.Sequence,
			&i.Validated,
			&i.MerchantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markQRCodeUsed = `-- name: MarkQRCodeUsed :one
UPDATE qr_codes
SET used = TRUE,
    used_by_user_id = $2,
    used_at = now()
WHERE id = $1
  AND used = FALSE
RETURNING id
`

type MarkQRCodeUsedParams struct {
	ID           string      `json:"id"`
	UsedByUserID pgtype.Text `json:"used_by_user_id"`
}

func (q *Queries) MarkQRCodeUsed(ctx context.Context, arg MarkQRCodeUsedParams) (string, error) {
	row := q.db.QueryRow(ctx, markQRCodeUsed, arg.ID, arg.UsedByUserID)
	var id string
	err := row.Scan(&id)
	return id, err
}
