// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    name,
    email,
    password_hash,
    profile_image_url
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, name, email, profile_image_url, active, created_at, updated_at
`

type CreateUserParams struct {
	ID              string      `json:"id"`
	Name            string      `json:"name"`
	Email           string      `json:"email"`
	PasswordHash    string      `json:"password_hash"`
	ProfileImageUrl pgtype.Text `json:"profile_image_url"`
}

type CreateUserRow struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	ProfileImageUrl pgtype.Text        `json:"profile_image_url"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.ProfileImageUrl,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ProfileImageUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserAuthByEmail = `-- name: GetUserAuthByEmail :one
SELECT id, name, email, password_hash, profile_image_url, active, created_at, updated_at
FROM users
WHERE email = $1
  AND active = TRUE
`

func (q *Queries) GetUserAuthByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserAuthByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.ProfileImageUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, profile_image_url, active, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	ProfileImageUrl pgtype.Text        `json:"profile_image_url"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ProfileImageUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = CASE
        WHEN $1::boolean THEN $2::text
        ELSE name
    END,
    profile_image_url = CASE
        WHEN $3::boolean THEN $4::text
        ELSE profile_image_url
    END,
    updated_at = now()
WHERE id = $5
RETURNING id, name, email, profile_image_url, active, created_at, updated_at
`

type UpdateUserParams struct {
	UpdateName      bool   `json:"update_name"`
	Name            string `json:"name"`
	UpdateImage     bool   `json:"update_image"`
	ProfileImageUrl string `json:"profile_image_url"`
	ID              string `json:"id"`
}

type UpdateUserRow struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	ProfileImageUrl pgtype.Text        `json:"profile_image_url"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UpdateName,
		arg.Name,
		arg.UpdateImage,
		arg.ProfileImageUrl,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ProfileImageUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
